site_name: AWS Inventory Scanner
site_description: A comprehensive AWS resource inventory scanner that discovers and catalogs AWS resources across all regions in your account.
site_author: "AWS Inventory Scanner Team"
repo_name: aws-inventory-scanner
repo_url: https://github.com/yourusername/aws-inventory-scanner
edit_uri: "edit/main/docs/"

plugins:
  - search
  - git-revision-date-localized
  - mkdocs-video

theme:
  name: material
  language: en
  features:
    - search.highlight
    - search.share
    - content.code.annotate
    - navigation.top
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Supported Services: services.md
  - Output Format: output.md
  - API Reference: api.md
  - Examples: examples.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
