name: mkdocs ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      # - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git@9.4.8-insiders-4.43.0
      - run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material.git@9.6.12
      # mkdocs-material-9.6.12
      - run: pip install mkdocs mkdocs-material mkdocs-git-revision-date-localized-plugin mkdocs-video pymarkdownlnt invoke watchdog

      - run: mkdocs gh-deploy --force